### ISSUE TITLE
Allow Inserting Media Folder Paths Manually

### ISSUE THREAD

**Issue by r3surrection** [jaruba/rpdb-folders#1]
I am trying to use your Tool on a Seedbox with 34 drives.
Nothing is happening if i click one of the Mountpoints...because i dont have permission for /home/hd27/ i only have permissions for /home/hd27/myusername...

Best regards

r3s
![image](https://user-images.githubusercontent.com/51033898/111181983-c7ee0280-85ae-11eb-9627-9fcbe0219a6f.png)

**Comment by jaruba** [comment]
@r3surrection I will add a way that will allow adding paths manually too, I will be able to do this in a few days, as I don't have access to all my equipment for testing right now.

Until then, you can also do this by editing the config file. (this is just an alternative)

The config file should be located at:
- OSX: `~/Library/Application Support/RPDB-Folders/config.json`
- Win: `%localappdata%\RPDB-Folders\config.json`
- Linux: `~/.config/RPDB-Folders/config.json`
- Docker: `<data path>/config.json`

Opening this file, it should look similar to:
https://github.com/jaruba/rpdb-folders/blob/a2ebf75e2b669357447c82ff6f0acfc6ceeebb97/config.js#L24-L36

Notice this part:
```
mediaFolders: { movie: [], series: [] },
```

Let's presume you want to add the folders: `/home/media/movies`, `/home/media/movies2`, `/home/media/series` and `/home/media/series2`, you would need to change this part of the config to:
```
mediaFolders: { movie: ["/home/media/movies","/home/media/movies2"], series: ["/home/media/series","/home/media/series2"] },
```

After making this change, I suggest to copy the contents of the entire file and pasting them on a JSON validator website, such as this: http://json.parser.online.fr/

If that website says that it is valid JSON, then save the file and start RPDB Folders after that, it should then start loading all your folders in the app.

**Comment by r3surrection** [comment]
That works, thanks!

**Comment by jaruba** [comment]
I am reopening the issue as I still want to add this feature.

**Comment by jaruba** [comment]
I have added this feature in RPDB Folders v0.0.7
